# Generated by Django 6.1.2 on 2026-10-08 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10, unique=True)),
                ('floor', models.CharField(max_length=50)),
                ('room_type', models.CharField(max_length=10)),
                ('capacity', models.PositiveIntegerField()),
                ('price_per_space', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('gender_policy', models.CharField(choices=[('UNASSIGNED', 'Unassigned'), ('MALE', 'Male'), ('FEMALE', 'Female')], default='UNASSIGNED', max_length=10)),
                ('amenities', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='RoomSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space_identifier', models.CharField(max_length=5)),
            ],
        ),
    ]
