# Generated by Django 6.1.2 on 2026-10-08 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='roomspace',
            name='occupant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roomspace', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roomspace',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to='rooms.room'),
        ),
        migrations.AlterUniqueTogether(
            name='roomspace',
            unique_together={('room', 'space_identifier')},
        ),
    ]
